name: projeto_detran
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.2.1           # sua vers찾o atual, ok
  latlong2: ^0.9.0              # sua vers찾o atual, ok
  shared_preferences: ^2.1.1    # sua vers찾o atual, ok

  geolocator: ^9.0.2
  http: ^1.4.0

  provider: ^6.0.5              # s처 se usar provider para tema ou estado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
